#azure-pipelines.yml


# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build

    pool:
      vmImage: 'windows-latest'
      demands:
      - msbuild
      - visualstudio
      - vstest


    variables:
      buildConfiguration: 'Release'
      
    steps:
    # Nuget Tool Installer Task
    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet 5.5.1'
      inputs:
        versionSpec: 5.5.1      

    # Nuget Restore Task
    - task: NuGetCommand@2
      displayName: 'NuGet restore'
      inputs:
        restoreSolution: '**/tailspintoysweb.csproj'

    # Node.js Tool Installer Task
    # Finds or downloads and caches the specified version spec of Node.js and adds it to the PATH
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x' 

    # Build Task  
    - task: DotNetCoreCLI@2
      displayName: 'Build solution'
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'  
        zipAfterPublish: true

    # Publish Task
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: 'drop'
      condition: succeededOrFailed()

- stage: DevDeploy  
  displayName: 'DevDeploy Stage'
  jobs:
  - job: Deploy
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      name: Hosted VS2017
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        downloadPath: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'LabConnection'
        appType: 'webApp'
        WebAppName: 'tailspintoys-dev-gjwk2in6pmhrw'
        deployToSlotOrASE: true
        ResourceGroupName: 'TailSpinToysRG'
        SlotName: 'staging'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/drop/*.zip'
        
- stage: TestDeploy  
  displayName: 'TestDeploy Stage'
  jobs:
  - job: Deploy
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      name: Hosted VS2017
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        downloadPath: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'LabConnection'
        appType: 'webApp'
        WebAppName: 'tailspintoys-test-gjwk2in6pmhrw' 
        deployToSlotOrASE: true
        ResourceGroupName: 'TailSpinToysRG'
        SlotName: 'staging'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/drop/*.zip'

- stage: ProductionDeploy  
  displayName: 'ProductionDeploy Stage'
  jobs:
  - job: Deploy
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    pool:
      name: Hosted VS2017
    steps:
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        downloadPath: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'LabConnection'
        appType: 'webApp'
        WebAppName: 'tailspintoys-production-gjwk2in6pmhrw' 
        deployToSlotOrASE: true
        ResourceGroupName: 'TailSpinToysRG'
        SlotName: 'staging'
        packageForLinux: '$(Build.ArtifactStagingDirectory)/drop/*.zip'
